### ISSUE TITLE
Mandelbrot set 

### ISSUE THREAD

**Issue by profdangarcia** [gabriel-msilva/melloc#1]
- First example of section **[Mandelbrot set ](https://gabriel-msilva.github.io/post/2022-02-08-mandelbrot-and-julia-sets/#mandelbrot-set)**, _c_ should be equals to 1.

**Comment by gabriel-msilva** [comment]
Thanks for pointing out @profdangarcia! Merged PR #2 
Website will be updated after Enhancement #3
